name: CD

on:
  push:

env:
  IMAGE: "ghcr.io/team-base64/edu-crm-tg-slave-bot-app"
  CONTAINER: "tg-slave-bot"

permissions:
  contents: read
  packages: write

jobs:
  build:
    if: contains(github.event.head_commit.message, '[DEPLOY]')
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}:latest
