name: CD

on:
  push:

env:
  REGISTRY: "Team-Base64/edu-crm-tg-slave-bot-app"
  TAG: "latest"
  CONTAINER_NAME: "tg-slave-bot"

jobs:
  build:
    if: contains(github.event.head_commit.message, '[DEPLOY]')
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: "${{ env.REGISTRY }}:${{ env.TAG }}"
